### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by PancakesArchitect** [SC-One/DropDownInputQML#3]
Hello again,

I've embedded this component in a project of mine and fixed a few things to turn it into a pure QML control (no CPP sort filter model, but really liked what you did with that), [demo here](https://bafybeie6t33fhls3yx26swj3x3polqxe4ardvixk3xzap7vis6ltxo7nxe.ipfs.dweb.link/dvoz-tags.mp4).

Wanted to congratulate you first, and ask you about the licensing details of [DropDownInputQML](https://github.com/SC-One/DropDownInputQML), as i'd like to distribute it in my project.

One issue i had was with the *DropDownInput* component taking way too much space, fixed it with:

```qml
implicitHeight: colLayout.implicitHeight
```

Thank you.

**Comment by SC-One** [comment]
Hello, I'm happy that the component was useful to you. (If you have a good idea for changing the UI, you can share it with me in the form of a picture, and I will try to implement it because the UI in the current version is not very good.)

**So do you think people like you who need this component would like which license?** I will add the license to the project. Feel free to use it anywhere; it's completely free.

**Comment by PancakesArchitect** [comment]
I think the UI is good, but there are issues with the layouts. I will make a PR to backport the small layout fixes. Will definitely share ideas with pictures/videos. One thing i've changed, is that when you click on a tag in the tag items view, it directly adds it to the chosen tags, instead of just inserting the tag name in the text field, i find that behaviour more intuitive.

> So do you think people like you who need this component would like which license

I think that using the MIT license would be a good choice for this project.
